/**
 * Texte des Funnels /app/start (18-NAECHSTES-LEVEL Hebel 1): Fragen, Ergebnis, Dokumentenlisten, Zeitplan, Aktionen.
 * Zahlen: Preise aus facts.ts, Sperrbetrag aus loan-copy.ts; Wechselkurs und Gebuehren sind Beispielwerte, im Ergebnis
 * als solche beschriftet. Urdu und Punjabi (Shahmukhi) sind vollwertige Sprachfassungen (Jan 19.09.).
 */
import type { Locale } from './i18n';

/** Beispielkurs PKR je EUR fuer den Rupien-Rechner; der Nutzer kann ihn im Ergebnis ueberschreiben */
export const PKR_PER_EUR_EXAMPLE = 310;
/** Beispiel: Gebuehr des Zahlungspartners in Prozent des Betrags (Platzhalter, bis der Partner feststeht) */
export const TRANSFER_FEE_PCT_EXAMPLE = 0.9;
/** Beispiel-Monatspraemien (aus den Preiskarten der Versicherungsseite) */
export const PREMIUM = { statutoryStudent: 120, privateStudent: 125.86, privateOther: 180 };

export type Group = 'study' | 'work';
export const GROUP_OF = (optionIndex: number): Group => (optionIndex < 7 ? 'study' : 'work');

export interface FunnelCopy {
  qFrom: string; fromIslamabad: string; fromKarachi: string; fromNote: string;
  qEmail: string; emailNote: string; skip: string;
  resultKicker: string; resultTitle: string; resultLead: string;
  setupLabel: string; setupComplete: string; setupWhy: Record<Group, string>; noSetupFee: string; depositSubWork: string; nothingToTransfer: string;
  fundLabel: string; fund: Record<'need' | 'have' | 'work', { title: string; text: string }>; guarantorNote: string; loanQ: string; loanYes: string; loanNo: string; tlLoan: string;
  moneyTitle: string; deposit: string; depositSub: string; rate: string; rateNote: string; inPkr: string; transferFee: string; totalEur: string; totalPkr: string; feeNote: string;
  insuranceTitle: string; statutory: string; privatePlan: string; premiumNote: string; billedOnArrival: string;
  docsTitle: string; docsLead: string; docs: Record<Group, string[]>; docsCommon: string[];
  timelineTitle: string; timelineLead: string; tl: { key: string; label: string; weeks: number }[]; today: string; arrival: string;
  arrivalPick: { winter: string; summer: string; other: string }; // M11: Semesterkarten und "anderer Monat" im Ankunftsschritt
  embassyTitle: string; embassy: Record<'islamabad' | 'karachi', string>; embassyWait: string;
  actions: string; whatsapp: string; print: string; createAccount: string; whatsappText: string;
  disclaimer: string;
  calendar: string; calendarTitle: string; privacy: string; noCheck: string;
  start: { items: string[]; meta: string[]; existing: string }; docsProgress: string; glance: { total: string; appt: string; docs: string };
  acct: { kicker: string; title: string; lead: string; summary: string; emailErr: string; pwHint: string; pwErr: string; show: string; hide: string; strength: [string, string, string]; consent: string; terms: string; privacyPolicy: string; doneTitle: string; doneText: string; doneSteps: string[]; goPortal: string; free: string };
}

const en: FunnelCopy = {
  qFrom: 'Where will you apply for your visa?', fromIslamabad: 'German Embassy Islamabad', fromKarachi: 'Consulate General Karachi', fromNote: 'Punjab, KP, Gilgit-Baltistan, AJK and Islamabad apply in Islamabad; Sindh and Balochistan in Karachi.',
  qEmail: 'Where should we send your plan?', emailNote: 'Optional. We send the summary once; no newsletter.', skip: 'Skip, show my plan',
  resultKicker: 'Your plan', resultTitle: 'Here is your setup, your money and your timeline', resultLead: 'Based on your answers. Nothing is booked yet; you can change every answer.',
  setupLabel: 'Recommended setup', setupComplete: 'Complete Setup',
  setupWhy: { study: 'Your student visa asks for proof of funds and health insurance. The Complete Setup covers both in one application and adds the Bank Account your payouts land in.', work: 'The Opportunity Card and the job-seeker visa ask for proof of funds and health cover. The Complete Setup covers both and gives you a German IBAN before you have a job.' },
  noSetupFee: 'no set-up fee', depositSubWork: '€1,091 × 12 months, set by the German authorities for the job-seeker visa and the Opportunity Card', nothingToTransfer: 'Nothing to transfer before departure: the partner bank pays the deposit in.',
  fundLabel: 'Your financing', fund: { need: { title: 'Interest-free study loan', text: 'The partner bank pays the deposit into your Blocked Account. We pay the interest to the bank. You repay only what you received, from the seventh month after arrival; the instalment plan comes from the partner bank.' }, have: { title: '€500 after your third payout', text: 'You transfer the deposit yourself. After your visa is approved and your third monthly payout has gone through, we send you €500 to your German Bank Account.' }, work: { title: 'You bring the deposit', text: 'The interest-free study loan is available for student visas. You transfer the deposit in rupees through our payments partner.' } }, guarantorNote: 'The partner bank needs a guarantor in Pakistan with a regular income or collateral; we help you prepare that before the application.', loanQ: 'Do you have a guarantor in Pakistan with a regular income, or collateral the partner bank accepts?', loanYes: 'Yes', loanNo: 'Not yet', tlLoan: 'Partner bank pays the deposit into your Blocked Account',
  moneyTitle: 'Your money, in euros and rupees', deposit: 'Blocked Account deposit', depositSub: '€992 × 12 months, set by the German authorities', rate: 'Exchange rate (PKR per EUR)', rateNote: 'Example rate. Enter today\'s rate to update the rupee amounts.', inPkr: 'in rupees', transferFee: 'Transfer fee (payments partner)', totalEur: 'Total to transfer before departure', totalPkr: 'in rupees, at your rate', feeNote: 'Fee shown as an example ([PLACEHOLDER: partner fee]). You see the exact rate and fee before you confirm the transfer.',
  insuranceTitle: 'Your health insurance', statutory: 'Statutory student plan', privatePlan: 'Private plan', premiumNote: 'Estimated monthly premium, billed only after you arrive.', billedOnArrival: 'Nothing is due for insurance before you fly.',
  docsTitle: 'Documents for your appointment', docsLead: 'Tick them off as you go. The list is saved on this device.',
  docsCommon: ['Passport, valid at least 12 months beyond arrival', 'Two biometric photos (35 × 45 mm, recent)', 'Completed VIDEX application form, printed and signed', 'Appointment confirmation', 'Blocked Account confirmation letter (from your EC Assets portal)', 'Travel health insurance and German health insurance certificates (from your portal)', 'Visa fee of €75 in rupees, cash or as required by the mission'],
  docs: { study: ['Admission letter (Zulassung) or conditional admission from the university', 'Degree certificates and transcripts, HEC-attested, with certified translations', 'Language certificate (IELTS, TOEFL, TestDaF or DSH, as your course requires)', 'CV in tabular form and a motivation letter', 'Proof of previous studies or gap explanation, if applicable'],
          work: ['Degree certificate with HEC attestation and recognition (anabin or ZAB statement)', 'CV in tabular form and a motivation letter', 'Language certificate: German A1 or English B2 for Opportunity Card points', 'Proof of work experience (reference letters)'] },
  timelineTitle: 'Your timeline, counted back from arrival', timelineLead: 'Weeks are typical values; embassy waiting times change, so book the appointment as early as the embassy allows.',
  tl: [{ key: 'apply', label: 'Open the Complete Setup online', weeks: 16 }, { key: 'transfer', label: 'Transfer the deposit from Pakistan', weeks: 15 }, { key: 'letter', label: 'Confirmation letter and insurance certificates in your portal', weeks: 14 }, { key: 'appointment', label: 'Visa appointment at the embassy', weeks: 10 }, { key: 'decision', label: 'Visa decision (typical processing)', weeks: 4 }, { key: 'flight', label: 'Book the flight, pack the documents', weeks: 2 }, { key: 'arrive', label: 'Arrive, activate everything in the portal', weeks: 0 }],
  today: 'Today', arrival: 'Arrival',
  arrivalPick: { winter: 'Winter semester · from {month} {year}', summer: 'Summer semester · from {month} {year}', other: 'Another month' }, // M11
  embassyTitle: 'Where you apply', embassy: { islamabad: 'German Embassy Islamabad. Appointments are booked through the embassy\'s online system; students get their own category.', karachi: 'Consulate General Karachi. Appointments are booked through the consulate\'s online system; students get their own category.' }, embassyWait: 'Current waiting time for student appointments: [PLACEHOLDER: weeks]. Check the mission\'s website; it changes with the season.',
  actions: 'Take your plan with you', whatsapp: 'Send to WhatsApp', print: 'Print or save as PDF', createAccount: 'Create your account and start',
  whatsappText: 'My EC Assets plan',
  disclaimer: 'This plan is a mockup. Prices are our current prices; rates, fees, premiums and waiting times are examples until the partners are confirmed.',
  calendar: 'Add the visa appointment to your calendar', calendarTitle: 'Visa appointment at the German mission', privacy: 'Stays in your browser. Nothing is sent.', noCheck: 'No credit check at this step',
  start: { items: ['A personal plan with dates, counted back from your arrival', 'Your money in euros and rupees, before you transfer anything', 'The document list for your embassy appointment'], meta: ['2 minutes', '6 questions', 'Nothing is sent'], existing: 'Already a customer?' }, docsProgress: '{a} of {b} ticked off', glance: { total: 'To transfer before departure', appt: 'Visa appointment', docs: 'Documents to prepare' },
  acct: { kicker: 'Last step', title: 'Save your plan and start', lead: 'Creating the account is free. Nothing is booked and nothing is charged until you activate in Germany.', summary: 'Your plan', emailErr: 'Please enter a valid email address.', pwHint: 'At least 8 characters. A mix of letters, numbers and symbols is strongest.', pwErr: 'Your password needs at least 8 characters.', show: 'Show', hide: 'Hide', strength: ['Weak', 'Okay', 'Strong'], consent: 'By creating an account you accept the {terms} and the {privacy}.', terms: 'Terms and Conditions', privacyPolicy: 'Privacy Policy', doneTitle: 'Your account is ready.', doneText: 'We saved your plan. Your portal shows every step, and we email you when something needs you.', doneSteps: ['Confirm your email address (link in your inbox)', 'Transfer the deposit; the confirmation letter follows the day it arrives', 'Activate after landing; your first payout follows within days'], goPortal: 'Open your portal', free: 'Free · no card needed' },
};

const ur: FunnelCopy = {
  qFrom: 'آپ ویزا کے لیے کہاں درخواست دیں گے؟', fromIslamabad: 'جرمن سفارت خانہ اسلام آباد', fromKarachi: 'قونصلیٹ جنرل کراچی', fromNote: 'پنجاب، خیبر پختونخوا، گلگت بلتستان، آزاد کشمیر اور اسلام آباد کے رہائشی اسلام آباد میں؛ سندھ اور بلوچستان کراچی میں درخواست دیتے ہیں۔',
  qEmail: 'ہم آپ کا منصوبہ کہاں بھیجیں؟', emailNote: 'اختیاری۔ ہم خلاصہ ایک بار بھیجتے ہیں؛ کوئی نیوز لیٹر نہیں۔', skip: 'چھوڑیں، میرا منصوبہ دکھائیں',
  resultKicker: 'آپ کا منصوبہ', resultTitle: 'یہ ہے آپ کا سیٹ اپ، آپ کی رقم اور آپ کا وقت', resultLead: 'آپ کے جوابات کی بنیاد پر۔ ابھی کچھ بک نہیں ہوا؛ آپ ہر جواب بدل سکتے ہیں۔',
  setupLabel: 'تجویز کردہ سیٹ اپ', setupComplete: 'کمپلیٹ سیٹ اپ',
  setupWhy: { study: 'آپ کے اسٹوڈنٹ ویزا کے لیے مالی ثبوت اور ہیلتھ انشورنس درکار ہے۔ کمپلیٹ سیٹ اپ دونوں کو ایک درخواست میں سمیٹتا ہے اور وہ بینک اکاؤنٹ دیتا ہے جس میں آپ کی ادائیگیاں آتی ہیں۔', work: 'آپرچونٹی کارڈ اور جاب سیکر ویزا کے لیے مالی ثبوت اور ہیلتھ کور درکار ہے۔ کمپلیٹ سیٹ اپ دونوں دیتا ہے اور نوکری سے پہلے ہی جرمن IBAN۔' },
  noSetupFee: 'کوئی سیٹ اپ فیس نہیں', depositSubWork: '1,091 یورو × 12 ماہ، جاب سیکر ویزا اور آپرچونٹی کارڈ کے لیے جرمن حکام کی طرف سے مقرر', nothingToTransfer: 'روانگی سے پہلے کچھ بھیجنا نہیں: پارٹنر بینک رقم جمع کرتا ہے۔',
  fundLabel: 'آپ کی فنانسنگ', fund: { need: { title: 'سود سے پاک تعلیمی قرض', text: 'پارٹنر بینک رقم آپ کے بلاکڈ اکاؤنٹ میں جمع کرتا ہے۔ سود ہم بینک کو ادا کرتے ہیں۔ آپ صرف وہی واپس کرتے ہیں جو آپ کو ملا، آمد کے بعد ساتویں مہینے سے؛ قسطوں کا منصوبہ پارٹنر بینک دیتا ہے۔' }, have: { title: 'تیسری ادائیگی کے بعد 500 یورو', text: 'آپ رقم خود ٹرانسفر کرتے ہیں۔ ویزا منظور ہونے اور تیسری ماہانہ ادائیگی کے بعد ہم آپ کے جرمن بینک اکاؤنٹ میں 500 یورو بھیجتے ہیں۔' }, work: { title: 'آپ خود رقم لاتے ہیں', text: 'سود سے پاک تعلیمی قرض اسٹوڈنٹ ویزا کے لیے دستیاب ہے۔ آپ رقم ہمارے پیمنٹ پارٹنر کے ذریعے روپوں میں ٹرانسفر کرتے ہیں۔' } }, guarantorNote: 'پارٹنر بینک کو پاکستان میں باقاعدہ آمدنی والا ضامن یا ضمانت درکار ہے؛ درخواست سے پہلے ہم اس کی تیاری میں مدد کرتے ہیں۔', loanQ: 'کیا پاکستان میں آپ کا کوئی ضامن ہے جس کی باقاعدہ آمدنی ہو، یا کوئی ضمانت جو پارٹنر بینک قبول کرے؟', loanYes: 'جی ہاں', loanNo: 'ابھی نہیں', tlLoan: 'پارٹنر بینک رقم آپ کے بلاکڈ اکاؤنٹ میں جمع کرتا ہے',
  moneyTitle: 'آپ کی رقم، یورو اور روپوں میں', deposit: 'بلاکڈ اکاؤنٹ کی رقم', depositSub: '992 یورو × 12 ماہ، جرمن حکام کی طرف سے مقرر', rate: 'شرحِ تبادلہ (روپے فی یورو)', rateNote: 'مثالی شرح۔ آج کی شرح لکھیں تو روپوں کی رقمیں بدل جاتی ہیں۔', inPkr: 'روپوں میں', transferFee: 'ٹرانسفر فیس (پیمنٹ پارٹنر)', totalEur: 'روانگی سے پہلے کل رقم', totalPkr: 'روپوں میں، آپ کی شرح پر', feeNote: 'فیس مثال کے طور پر ([PLACEHOLDER: partner fee])۔ تصدیق سے پہلے آپ اصل شرح اور فیس دیکھتے ہیں۔',
  insuranceTitle: 'آپ کی ہیلتھ انشورنس', statutory: 'سرکاری اسٹوڈنٹ پلان', privatePlan: 'پرائیویٹ پلان', premiumNote: 'تخمینی ماہانہ پریمیم، صرف پہنچنے کے بعد وصول۔', billedOnArrival: 'پرواز سے پہلے انشورنس کی کوئی رقم واجب نہیں۔',
  docsTitle: 'اپائنٹمنٹ کے لیے دستاویزات', docsLead: 'ساتھ ساتھ ٹک لگاتے جائیں۔ فہرست اسی آلے پر محفوظ رہتی ہے۔',
  docsCommon: ['پاسپورٹ، آمد کے بعد کم از کم 12 ماہ کارآمد', 'دو بایومیٹرک تصاویر (35 × 45 ملی میٹر، حالیہ)', 'مکمل VIDEX درخواست فارم، پرنٹ اور دستخط شدہ', 'اپائنٹمنٹ کی تصدیق', 'بلاکڈ اکاؤنٹ تصدیقی خط (آپ کے EC Assets پورٹل سے)', 'ٹریول اور جرمن ہیلتھ انشورنس سرٹیفکیٹ (پورٹل سے)', 'ویزا فیس 75 یورو روپوں میں، نقد یا مشن کی ہدایت کے مطابق'],
  docs: { study: ['یونیورسٹی کا داخلہ خط (Zulassung) یا مشروط داخلہ', 'ڈگری سرٹیفکیٹ اور ٹرانسکرپٹ، HEC سے تصدیق شدہ، مصدقہ ترجمے کے ساتھ', 'زبان کا سرٹیفکیٹ (IELTS، TOEFL، TestDaF یا DSH، کورس کے مطابق)', 'جدولی CV اور موٹیویشن لیٹر', 'سابقہ تعلیم کا ثبوت یا وقفے کی وضاحت، اگر لاگو ہو'],
          work: ['HEC تصدیق شدہ ڈگری اور اس کی شناخت (anabin یا ZAB بیان)', 'جدولی CV اور موٹیویشن لیٹر', 'زبان کا سرٹیفکیٹ: آپرچونٹی کارڈ پوائنٹس کے لیے جرمن A1 یا انگریزی B2', 'کام کے تجربے کا ثبوت (ریفرنس لیٹر)'] },
  timelineTitle: 'آپ کا وقت، آمد سے پیچھے گنا ہوا', timelineLead: 'ہفتے عام اندازے ہیں؛ سفارت خانے کے انتظار کے اوقات بدلتے ہیں، اس لیے اپائنٹمنٹ جتنی جلدی ممکن ہو بک کریں۔',
  tl: [{ key: 'apply', label: 'کمپلیٹ سیٹ اپ آن لائن کھولیں', weeks: 16 }, { key: 'transfer', label: 'پاکستان سے رقم بھیجیں', weeks: 15 }, { key: 'letter', label: 'تصدیقی خط اور انشورنس سرٹیفکیٹ پورٹل میں', weeks: 14 }, { key: 'appointment', label: 'سفارت خانے میں ویزا اپائنٹمنٹ', weeks: 10 }, { key: 'decision', label: 'ویزا فیصلہ (عام پروسیسنگ)', weeks: 4 }, { key: 'flight', label: 'پرواز بک کریں، دستاویزات سمیٹیں', weeks: 2 }, { key: 'arrive', label: 'پہنچیں، پورٹل میں سب کچھ فعال کریں', weeks: 0 }],
  today: 'آج', arrival: 'آمد',
  arrivalPick: { winter: 'سرمائی سمسٹر · {month} {year} سے', summer: 'گرمائی سمسٹر · {month} {year} سے', other: 'کوئی اور مہینہ' }, // M11 (Entwurf)
  embassyTitle: 'آپ کہاں درخواست دیتے ہیں', embassy: { islamabad: 'جرمن سفارت خانہ اسلام آباد۔ اپائنٹمنٹ سفارت خانے کے آن لائن نظام سے بک ہوتی ہے؛ طلبہ کا اپنا زمرہ ہے۔', karachi: 'قونصلیٹ جنرل کراچی۔ اپائنٹمنٹ قونصلیٹ کے آن لائن نظام سے بک ہوتی ہے؛ طلبہ کا اپنا زمرہ ہے۔' }, embassyWait: 'طلبہ کی اپائنٹمنٹ کا موجودہ انتظار: [PLACEHOLDER: weeks]۔ مشن کی ویب سائٹ دیکھیں؛ یہ موسم کے ساتھ بدلتا ہے۔',
  actions: 'اپنا منصوبہ ساتھ لے جائیں', whatsapp: 'واٹس ایپ پر بھیجیں', print: 'پرنٹ یا PDF محفوظ کریں', createAccount: 'اکاؤنٹ بنائیں اور شروع کریں',
  whatsappText: 'میرا EC Assets منصوبہ',
  disclaimer: 'یہ منصوبہ ایک ماک اپ ہے۔ قیمتیں ہماری موجودہ قیمتیں ہیں؛ شرح، فیس، پریمیم اور انتظار کے اوقات مثالیں ہیں جب تک پارٹنر طے نہ ہوں۔',
  calendar: 'ویزا اپائنٹمنٹ اپنے کیلنڈر میں شامل کریں', calendarTitle: 'جرمن مشن میں ویزا اپائنٹمنٹ', privacy: 'آپ کے براؤزر میں رہتا ہے۔ کچھ بھیجا نہیں جاتا۔', noCheck: 'اس مرحلے پر کوئی کریڈٹ چیک نہیں',
  start: { items: ['تاریخوں کے ساتھ ذاتی منصوبہ، آپ کی آمد سے پیچھے گنا ہوا', 'آپ کی رقم یورو اور روپوں میں، کچھ بھیجنے سے پہلے', 'سفارت خانے کی اپائنٹمنٹ کے لیے دستاویزات کی فہرست'], meta: ['2 منٹ', '6 سوالات', 'کچھ بھیجا نہیں جاتا'], existing: 'پہلے سے کسٹمر ہیں؟' }, docsProgress: '{b} میں سے {a} پر ٹک', glance: { total: 'روانگی سے پہلے ٹرانسفر', appt: 'ویزا اپائنٹمنٹ', docs: 'تیار کرنے کی دستاویزات' },
  acct: { kicker: 'آخری مرحلہ', title: 'اپنا منصوبہ محفوظ کریں اور شروع کریں', lead: 'اکاؤنٹ بنانا مفت ہے۔ جرمنی میں فعال کرنے تک کچھ بک نہیں ہوتا اور کچھ وصول نہیں ہوتا۔', summary: 'آپ کا منصوبہ', emailErr: 'براہِ کرم درست ای میل ایڈریس لکھیں۔', pwHint: 'کم از کم 8 حروف۔ حروف، اعداد اور علامات کا مرکب سب سے مضبوط ہے۔', pwErr: 'آپ کے پاس ورڈ میں کم از کم 8 حروف ہونے چاہئیں۔', show: 'دکھائیں', hide: 'چھپائیں', strength: ['کمزور', 'ٹھیک', 'مضبوط'], consent: 'اکاؤنٹ بنانے سے آپ {terms} اور {privacy} قبول کرتے ہیں۔', terms: 'شرائط و ضوابط', privacyPolicy: 'پرائیویسی پالیسی', doneTitle: 'آپ کا اکاؤنٹ تیار ہے۔', doneText: 'ہم نے آپ کا منصوبہ محفوظ کر لیا۔ آپ کا پورٹل ہر مرحلہ دکھاتا ہے، اور جب کچھ آپ سے چاہیے ہو تو ہم ای میل کرتے ہیں۔', doneSteps: ['اپنا ای میل ایڈریس تصدیق کریں (لنک آپ کے ان باکس میں)', 'رقم ٹرانسفر کریں؛ تصدیقی خط اسی دن آتا ہے جس دن رقم پہنچتی ہے', 'پہنچنے کے بعد فعال کریں؛ پہلی ادائیگی چند دنوں میں آتی ہے'], goPortal: 'اپنا پورٹل کھولیں', free: 'مفت · کارڈ کی ضرورت نہیں' },
};

const pa: FunnelCopy = {
  qFrom: 'تسیں ویزے لئی کتھے درخواست دیو گے؟', fromIslamabad: 'جرمن سفارت خانہ اسلام آباد', fromKarachi: 'قونصلیٹ جنرل کراچی', fromNote: 'پنجاب، خیبر پختونخوا، گلگت بلتستان، آزاد کشمیر تے اسلام آباد والے اسلام آباد وچ؛ سندھ تے بلوچستان والے کراچی وچ درخواست دیندے نیں۔',
  qEmail: 'اسیں تہاڈا منصوبہ کتھے بھیجیے؟', emailNote: 'اختیاری۔ اسیں خلاصہ اک واری بھیجدے آں؛ کوئی نیوز لیٹر نہیں۔', skip: 'چھڈو، میرا منصوبہ وکھاؤ',
  resultKicker: 'تہاڈا منصوبہ', resultTitle: 'ایہہ اے تہاڈا سیٹ اپ، تہاڈی رقم تے تہاڈا ویلا', resultLead: 'تہاڈے جواباں دی بنیاد تے۔ ہالے کجھ بک نہیں ہویا؛ تسیں ہر جواب بدل سکدے او۔',
  setupLabel: 'تجویز کیتا سیٹ اپ', setupComplete: 'کمپلیٹ سیٹ اپ',
  setupWhy: { study: 'تہاڈے سٹوڈنٹ ویزے لئی مالی ثبوت تے ہیلتھ انشورنس چاہیدی اے۔ کمپلیٹ سیٹ اپ دوویں اک درخواست وچ دیندا اے تے اوہ بینک اکاؤنٹ وی جتھے تہاڈیاں ادائیگیاں آندیاں نیں۔', work: 'آپرچونٹی کارڈ تے جاب سیکر ویزے لئی مالی ثبوت تے ہیلتھ کور چاہیدا اے۔ کمپلیٹ سیٹ اپ دوویں دیندا اے تے نوکری توں پہلاں ای جرمن IBAN۔' },
  noSetupFee: 'کوئی سیٹ اپ فیس نہیں', depositSubWork: '1,091 یورو × 12 مہینے، جاب سیکر ویزے تے آپرچونٹی کارڈ لئی جرمن حکام ولوں مقرر', nothingToTransfer: 'روانگی توں پہلاں کجھ بھیجݨا نہیں: پارٹنر بینک رقم جمع کردا اے۔',
  fundLabel: 'تہاڈی فنانسنگ', fund: { need: { title: 'بغیر سود تعلیمی قرضہ', text: 'پارٹنر بینک رقم تہاڈے بلاکڈ اکاؤنٹ وچ جمع کردا اے۔ سود اسیں بینک نوں دیندے آں۔ تسیں صرف اوہی واپس کردے او جو تہانوں ملیا، آمد توں بعد ستویں مہینے توں؛ قسطاں دا منصوبہ پارٹنر بینک دیندا اے۔' }, have: { title: 'تیجی ادائیگی توں بعد 500 یورو', text: 'تسیں رقم آپ ٹرانسفر کردے او۔ ویزا منظور ہوݨ تے تیجی مہینے دی ادائیگی توں بعد اسیں تہاڈے جرمن بینک اکاؤنٹ وچ 500 یورو بھیجدے آں۔' }, work: { title: 'تسیں آپ رقم لیاندے او', text: 'بغیر سود تعلیمی قرضہ سٹوڈنٹ ویزے لئی اے۔ تسیں رقم ساڈے پیمنٹ پارٹنر راہیں روپیاں وچ ٹرانسفر کردے او۔' } }, guarantorNote: 'پارٹنر بینک نوں پاکستان وچ باقاعدہ آمدن والا ضامن یا ضمانت چاہیدی اے؛ درخواست توں پہلاں اسیں ایہدی تیاری وچ مدد کردے آں۔', loanQ: 'کیہ پاکستان وچ تہاڈا کوئی ضامن اے جیہدی باقاعدہ آمدن ہووے، یا کوئی ضمانت جیہڑی پارٹنر بینک منّے؟', loanYes: 'ہاں', loanNo: 'ہالے نہیں', tlLoan: 'پارٹنر بینک رقم تہاڈے بلاکڈ اکاؤنٹ وچ جمع کردا اے',
  moneyTitle: 'تہاڈی رقم، یورو تے روپیاں وچ', deposit: 'بلاکڈ اکاؤنٹ دی رقم', depositSub: '992 یورو × 12 مہینے، جرمن حکام ولوں مقرر', rate: 'شرحِ تبادلہ (روپے فی یورو)', rateNote: 'مثالی شرح۔ اج دی شرح لکھو تے روپیاں دیاں رقماں بدل جاندیاں نیں۔', inPkr: 'روپیاں وچ', transferFee: 'ٹرانسفر فیس (پیمنٹ پارٹنر)', totalEur: 'روانگی توں پہلاں کل رقم', totalPkr: 'روپیاں وچ، تہاڈی شرح تے', feeNote: 'فیس مثال دے طور تے ([PLACEHOLDER: partner fee])۔ تصدیق توں پہلاں تسیں اصل شرح تے فیس ویکھدے او۔',
  insuranceTitle: 'تہاڈی ہیلتھ انشورنس', statutory: 'سرکاری سٹوڈنٹ پلان', privatePlan: 'پرائیویٹ پلان', premiumNote: 'اندازاً مہینے دا پریمیم، صرف پہنچݨ توں بعد۔', billedOnArrival: 'اڈاݨ توں پہلاں انشورنس دی کوئی رقم واجب نہیں۔',
  docsTitle: 'اپائنٹمنٹ لئی دستاویزاں', docsLead: 'نال نال ٹک لاندے جاؤ۔ لسٹ ایسے ڈیوائس تے محفوظ رہندی اے۔',
  docsCommon: ['پاسپورٹ، آمد توں بعد گھٹو گھٹ 12 مہینے کارآمد', 'دو بایومیٹرک تصویراں (35 × 45 ملی میٹر، حالیہ)', 'مکمل VIDEX درخواست فارم، پرنٹ تے دستخط شدہ', 'اپائنٹمنٹ دی تصدیق', 'بلاکڈ اکاؤنٹ تصدیقی خط (تہاڈے EC Assets پورٹل توں)', 'ٹریول تے جرمن ہیلتھ انشورنس سرٹیفکیٹ (پورٹل توں)', 'ویزا فیس 75 یورو روپیاں وچ، نقد یا مشن دی ہدایت موجب'],
  docs: { study: ['یونیورسٹی دا داخلہ خط (Zulassung) یا مشروط داخلہ', 'ڈگری سرٹیفکیٹ تے ٹرانسکرپٹ، HEC توں تصدیق شدہ، مصدقہ ترجمے نال', 'زبان دا سرٹیفکیٹ (IELTS، TOEFL، TestDaF یا DSH، کورس موجب)', 'جدولی CV تے موٹیویشن لیٹر', 'پچھلی پڑھائی دا ثبوت یا وقفے دی وضاحت، جے لاگو ہووے'],
          work: ['HEC تصدیق شدہ ڈگری تے اوہدی پچھاݨ (anabin یا ZAB بیان)', 'جدولی CV تے موٹیویشن لیٹر', 'زبان دا سرٹیفکیٹ: آپرچونٹی کارڈ پوائنٹس لئی جرمن A1 یا انگریزی B2', 'کم دے تجربے دا ثبوت (ریفرنس لیٹر)'] },
  timelineTitle: 'تہاڈا ویلا، آمد توں پچھے گݨیا', timelineLead: 'ہفتے عام اندازے نیں؛ سفارت خانے دے انتظار دے ویلے بدلدے نیں، ایس لئی اپائنٹمنٹ جنی چھیتی ہو سکے بک کرو۔',
  tl: [{ key: 'apply', label: 'کمپلیٹ سیٹ اپ آن لائن کھولو', weeks: 16 }, { key: 'transfer', label: 'پاکستان توں رقم بھیجو', weeks: 15 }, { key: 'letter', label: 'تصدیقی خط تے انشورنس سرٹیفکیٹ پورٹل وچ', weeks: 14 }, { key: 'appointment', label: 'سفارت خانے وچ ویزا اپائنٹمنٹ', weeks: 10 }, { key: 'decision', label: 'ویزا فیصلہ (عام پروسیسنگ)', weeks: 4 }, { key: 'flight', label: 'فلائٹ بک کرو، دستاویزاں سمیٹو', weeks: 2 }, { key: 'arrive', label: 'پہنچو، پورٹل وچ سب کجھ فعال کرو', weeks: 0 }],
  today: 'اج', arrival: 'آمد',
  arrivalPick: { winter: 'سیالے دا سمسٹر · {month} {year} توں', summer: 'گرمیاں دا سمسٹر · {month} {year} توں', other: 'کوئی ہور مہینہ' }, // M11 (Entwurf)
  embassyTitle: 'تسیں کتھے درخواست دیندے او', embassy: { islamabad: 'جرمن سفارت خانہ اسلام آباد۔ اپائنٹمنٹ سفارت خانے دے آن لائن سسٹم توں بک ہوندی اے؛ طالب علماں دا آپݨا زمرہ اے۔', karachi: 'قونصلیٹ جنرل کراچی۔ اپائنٹمنٹ قونصلیٹ دے آن لائن سسٹم توں بک ہوندی اے؛ طالب علماں دا آپݨا زمرہ اے۔' }, embassyWait: 'طالب علماں دی اپائنٹمنٹ دا موجودہ انتظار: [PLACEHOLDER: weeks]۔ مشن دی ویب سائٹ ویکھو؛ ایہہ موسم نال بدلدا اے۔',
  actions: 'آپݨا منصوبہ نال لے جاؤ', whatsapp: 'واٹس ایپ تے بھیجو', print: 'پرنٹ یا PDF محفوظ کرو', createAccount: 'اکاؤنٹ بݨاؤ تے شروع کرو',
  whatsappText: 'میرا EC Assets منصوبہ',
  disclaimer: 'ایہہ منصوبہ اک ماک اپ اے۔ قیمتاں ساڈیاں موجودہ قیمتاں نیں؛ شرح، فیس، پریمیم تے انتظار دے ویلے مثالاں نیں جد تک پارٹنر طے نہ ہوݨ۔',
  calendar: 'ویزا اپائنٹمنٹ آپݨے کیلنڈر وچ شامل کرو', calendarTitle: 'جرمن مشن وچ ویزا اپائنٹمنٹ', privacy: 'تہاڈے براؤزر وچ رہندا اے۔ کجھ بھیجیا نہیں جاندا۔', noCheck: 'ایس قدم تے کوئی کریڈٹ چیک نہیں',
  start: { items: ['تاریخاں نال ذاتی منصوبہ، تہاڈی آمد توں پچھے گنیا ہویا', 'تہاڈی رقم یورو تے روپیاں وچ، کجھ بھیجݨ توں پہلاں', 'سفارت خانے دی اپائنٹمنٹ لئی دستاویزاں دی لسٹ'], meta: ['2 منٹ', '6 سوال', 'کجھ بھیجیا نہیں جاندا'], existing: 'پہلاں توں گاہک او؟' }, docsProgress: '{b} وچوں {a} تے ٹک', glance: { total: 'روانگی توں پہلاں ٹرانسفر', appt: 'ویزا اپائنٹمنٹ', docs: 'تیار کرݨ دیاں دستاویزاں' },
  acct: { kicker: 'آخری قدم', title: 'آپݨا منصوبہ محفوظ کرو تے شروع کرو', lead: 'اکاؤنٹ بݨاؤݨا مفت اے۔ جرمنی وچ فعال کرݨ تک کجھ بک نہیں ہوندا تے کجھ وصول نہیں ہوندا۔', summary: 'تہاڈا منصوبہ', emailErr: 'مہربانی کر کے درست ای میل ایڈریس لکھو۔', pwHint: 'گھٹو گھٹ 8 حرف۔ حرفاں، نمبراں تے نشاناں دا ملاپ سبھ توں مضبوط اے۔', pwErr: 'تہاڈے پاس ورڈ وچ گھٹو گھٹ 8 حرف ہوݨے چاہیدے نیں۔', show: 'وکھاؤ', hide: 'لکاؤ', strength: ['کمزور', 'ٹھیک', 'مضبوط'], consent: 'اکاؤنٹ بݨاؤݨ نال تسیں {terms} تے {privacy} قبول کردے او۔', terms: 'شرطاں تے ضابطے', privacyPolicy: 'پرائیویسی پالیسی', doneTitle: 'تہاڈا اکاؤنٹ تیار اے۔', doneText: 'اسیں تہاڈا منصوبہ محفوظ کر لیا۔ تہاڈا پورٹل ہر قدم وکھاندا اے، تے جدوں کجھ تہاڈے کولوں چاہیدا ہووے تے اسیں ای میل کردے آں۔', doneSteps: ['آپݨا ای میل ایڈریس تصدیق کرو (لنک تہاڈے ان باکس وچ)', 'رقم ٹرانسفر کرو؛ تصدیقی خط اوسے دن آندا اے جس دن رقم پہنچدی اے', 'پہنچݨ توں بعد فعال کرو؛ پہلی ادائیگی کجھ دناں وچ آندی اے'], goPortal: 'آپݨا پورٹل کھولو', free: 'مفت · کارڈ دی لوڑ نہیں' },
};

export const FUNNEL: Record<Locale, FunnelCopy> = { en, ur, pa };
