/**
 * Texte des Portal-Prototyps /app/* (18-NAECHSTES-LEVEL Hebel 4): Ueberweisung, Dokumente, Aktivierung.
 * Bankdaten sind Platzhalter, bis die Partnerbank feststeht. Urdu und Punjabi (Shahmukhi) sind vollwertige Sprachfassungen (Jan 19.09.).
 */
import type { Locale } from './i18n';
export interface PortalCopy {
  nav: { dashboard: string; transfer: string; documents: string; activate: string; settings: string };
  transfer: { kicker: string; title: string; lead: string; to: string; bank: string; iban: string; bic: string; reference: string; amount: string; note: string; copy: string; copied: string; status: string; steps: string[]; sent: string; sentDone: string; partner: string; partnerText: string };
  documents: { kicker: string; title: string; lead: string; ready: string; pending: string; download: string; items: { name: string; state: 'ready' | 'pending'; note: string }[]; preview: string };
  activate: { kicker: string; title: string; lead: string; arrival: string; address: string; addressNote: string; upload: string; button: string; done: string; doneText: string; payout: string; steps: string[] };
}
const en: PortalCopy = {
  nav: { dashboard: 'Dashboard', transfer: 'Transfer', documents: 'Documents', activate: 'Activate', settings: 'Settings' },
  transfer: { kicker: 'Step 2 of 4', title: 'Transfer your deposit', lead: 'Send exactly this amount with exactly this reference. The confirmation letter is issued the day the money arrives.', to: 'Account holder', bank: 'Bank', iban: 'IBAN', bic: 'BIC', reference: 'Payment reference', amount: 'Amount', note: 'Your name and this reference must appear on the transfer, otherwise the bank cannot match it.', copy: 'Copy', copied: 'Copied', status: 'Where your money is', steps: ['Transfer instructed', 'Received by the payments partner', 'Converted and forwarded', 'Arrived in your Blocked Account'], sent: 'I have sent the money', sentDone: 'Thanks. We will confirm receipt by email and in this portal; most transfers from Pakistan arrive within 2 to 4 business days.', partner: 'Paying in rupees?', partnerText: 'Our payments partner takes rupees in Pakistan and pays euros into your account; you see the rate and the fee before you confirm. [PLACEHOLDER: partner name and link]' },
  documents: { kicker: 'Your file', title: 'Documents for the embassy', lead: 'Everything the visa appointment asks for from us, as PDF. Print each one; the missions want paper.', ready: 'Ready', pending: 'Pending', download: 'Download PDF', items: [{ name: 'Blocked Account confirmation letter', state: 'pending', note: 'Issued the day your deposit arrives' }, { name: 'Travel health insurance certificate', state: 'ready', note: 'Valid from your arrival date until your German cover starts' }, { name: 'German health insurance certificate', state: 'pending', note: 'Issued once you choose your plan' }, { name: 'Bank Account IBAN letter', state: 'pending', note: 'Available after activation in Germany' }], preview: 'Preview of the confirmation letter' },
  activate: { kicker: 'Step 4 of 4', title: 'Activate after arrival', lead: 'One step once you are in Germany: tell us the date you arrived and where you registered. Your first payout follows within days.', arrival: 'Date of arrival', address: 'German address', addressNote: 'As registered at the citizens\' office (Anmeldung). You can add the registration certificate later.', upload: 'Upload registration certificate (optional)', button: 'Activate my products', done: 'Everything is active', doneText: 'Blocked Account payouts start, your health insurance is switched on and your card is live in the app. First payout:', payout: '€992', steps: ['Arrival date confirmed', 'Address registered', 'Blocked Account activated', 'Health insurance active', 'Bank Account and card active'] },
};
const ur: PortalCopy = {
  nav: { dashboard: 'ڈیش بورڈ', transfer: 'ٹرانسفر', documents: 'دستاویزات', activate: 'فعال کریں', settings: 'ترتیبات' },
  transfer: { kicker: '4 میں سے مرحلہ 2', title: 'اپنی رقم ٹرانسفر کریں', lead: 'بالکل یہی رقم بالکل اسی حوالے کے ساتھ بھیجیں۔ تصدیقی خط اسی دن جاری ہوتا ہے جس دن رقم پہنچتی ہے۔', to: 'اکاؤنٹ ہولڈر', bank: 'بینک', iban: 'IBAN', bic: 'BIC', reference: 'ادائیگی کا حوالہ', amount: 'رقم', note: 'ٹرانسفر پر آپ کا نام اور یہ حوالہ ضرور ہو، ورنہ بینک اسے ملا نہیں سکتا۔', copy: 'کاپی', copied: 'کاپی ہو گیا', status: 'آپ کی رقم کہاں ہے', steps: ['ٹرانسفر کی ہدایت دی گئی', 'پیمنٹ پارٹنر کو موصول', 'تبدیل اور آگے بھیجی گئی', 'آپ کے بلاکڈ اکاؤنٹ میں پہنچ گئی'], sent: 'میں نے رقم بھیج دی ہے', sentDone: 'شکریہ۔ ہم وصولی کی تصدیق ای میل اور اس پورٹل میں کریں گے؛ پاکستان سے زیادہ تر ٹرانسفر 2 سے 4 کاروباری دنوں میں پہنچتے ہیں۔', partner: 'روپوں میں ادا کر رہے ہیں؟', partnerText: 'ہمارا پیمنٹ پارٹنر پاکستان میں روپے لیتا ہے اور آپ کے اکاؤنٹ میں یورو جمع کرتا ہے؛ تصدیق سے پہلے آپ ریٹ اور فیس دیکھتے ہیں۔ [PLACEHOLDER: partner name and link]' },
  documents: { kicker: 'آپ کی فائل', title: 'سفارت خانے کے لیے دستاویزات', lead: 'ویزا اپائنٹمنٹ ہم سے جو مانگتی ہے، سب PDF میں۔ ہر ایک پرنٹ کریں؛ مشن کاغذ چاہتے ہیں۔', ready: 'تیار', pending: 'زیرِ التوا', download: 'PDF ڈاؤن لوڈ کریں', items: [{ name: 'بلاکڈ اکاؤنٹ تصدیقی خط', state: 'pending', note: 'جس دن رقم پہنچے، اسی دن جاری' }, { name: 'ٹریول ہیلتھ انشورنس سرٹیفکیٹ', state: 'ready', note: 'آپ کی آمد کی تاریخ سے آپ کی جرمن کوریج شروع ہونے تک کارآمد' }, { name: 'جرمن ہیلتھ انشورنس سرٹیفکیٹ', state: 'pending', note: 'پلان چننے کے بعد جاری' }, { name: 'بینک اکاؤنٹ IBAN خط', state: 'pending', note: 'جرمنی میں فعال کرنے کے بعد دستیاب' }], preview: 'تصدیقی خط کا پیش منظر' },
  activate: { kicker: '4 میں سے مرحلہ 4', title: 'پہنچنے کے بعد فعال کریں', lead: 'جرمنی پہنچ کر ایک قدم: ہمیں آمد کی تاریخ اور رجسٹریشن کی جگہ بتائیں۔ پہلی ادائیگی چند دنوں میں آتی ہے۔', arrival: 'آمد کی تاریخ', address: 'جرمن پتہ', addressNote: 'جیسا شہری دفتر میں رجسٹر ہے (Anmeldung)۔ رجسٹریشن سرٹیفکیٹ بعد میں بھی جوڑ سکتے ہیں۔', upload: 'رجسٹریشن سرٹیفکیٹ اپ لوڈ کریں (اختیاری)', button: 'میری پراڈکٹس فعال کریں', done: 'سب کچھ فعال ہے', doneText: 'بلاکڈ اکاؤنٹ کی ادائیگیاں شروع، آپ کی ہیلتھ انشورنس آن اور آپ کا کارڈ ایپ میں چالو۔ پہلی ادائیگی:', payout: '992 یورو', steps: ['آمد کی تاریخ تصدیق شدہ', 'پتہ رجسٹر شدہ', 'بلاکڈ اکاؤنٹ فعال', 'ہیلتھ انشورنس فعال', 'بینک اکاؤنٹ اور کارڈ فعال'] },
};
const pa: PortalCopy = {
  nav: { dashboard: 'ڈیش بورڈ', transfer: 'ٹرانسفر', documents: 'دستاویزاں', activate: 'فعال کرو', settings: 'ترتیباں' },
  transfer: { kicker: '4 وچوں قدم 2', title: 'آپݨی رقم ٹرانسفر کرو', lead: 'بالکل ایہو رقم بالکل ایسے حوالے نال بھیجو۔ تصدیقی خط اوسے دن جاری ہوندا اے جس دن رقم پہنچدی اے۔', to: 'اکاؤنٹ ہولڈر', bank: 'بینک', iban: 'IBAN', bic: 'BIC', reference: 'ادائیگی دا حوالہ', amount: 'رقم', note: 'ٹرانسفر تے تہاڈا ناں تے ایہہ حوالہ ضرور ہووے، نہیں تے بینک ایہنوں ملا نہیں سکدا۔', copy: 'کاپی', copied: 'کاپی ہو گیا', status: 'تہاڈی رقم کتھے اے', steps: ['ٹرانسفر دی ہدایت دتی گئی', 'پیمنٹ پارٹنر نوں ملی', 'بدلی تے اگے بھیجی گئی', 'تہاڈے بلاکڈ اکاؤنٹ وچ پہنچ گئی'], sent: 'میں رقم بھیج دتی اے', sentDone: 'شکریہ۔ اسیں وصولی دی تصدیق ای میل تے ایس پورٹل وچ کراں گے؛ پاکستان توں بہتے ٹرانسفر 2 توں 4 کاروباری دناں وچ پہنچدے نیں۔', partner: 'روپیاں وچ ادا کر رہے او؟', partnerText: 'ساڈا پیمنٹ پارٹنر پاکستان وچ روپے لیندا اے تے تہاڈے اکاؤنٹ وچ یورو جمع کردا اے؛ تصدیق توں پہلاں تسیں ریٹ تے فیس ویکھدے او۔ [PLACEHOLDER: partner name and link]' },
  documents: { kicker: 'تہاڈی فائل', title: 'سفارت خانے لئی دستاویزاں', lead: 'ویزا اپائنٹمنٹ ساڈے کولوں جو منگدی اے، سب PDF وچ۔ ہر اک پرنٹ کرو؛ مشن کاغذ چاہندے نیں۔', ready: 'تیار', pending: 'باقی', download: 'PDF ڈاؤن لوڈ کرو', items: [{ name: 'بلاکڈ اکاؤنٹ تصدیقی خط', state: 'pending', note: 'جس دن رقم پہنچے، اوسے دن جاری' }, { name: 'ٹریول ہیلتھ انشورنس سرٹیفکیٹ', state: 'ready', note: 'تہاڈی آمد دی تاریخ توں تہاڈی جرمن کوریج شروع ہوݨ تک کارآمد' }, { name: 'جرمن ہیلتھ انشورنس سرٹیفکیٹ', state: 'pending', note: 'پلان چݨن توں بعد جاری' }, { name: 'بینک اکاؤنٹ IBAN خط', state: 'pending', note: 'جرمنی وچ فعال کرن توں بعد دستیاب' }], preview: 'تصدیقی خط دا پیش منظر' },
  activate: { kicker: '4 وچوں قدم 4', title: 'پہنچݨ توں بعد فعال کرو', lead: 'جرمنی پہنچ کے اک قدم: ساہنوں آمد دی تاریخ تے رجسٹریشن دی تھاں دسو۔ پہلی ادائیگی کجھ دناں وچ آندی اے۔', arrival: 'آمد دی تاریخ', address: 'جرمن پتہ', addressNote: 'جویں شہری دفتر وچ رجسٹر اے (Anmeldung)۔ رجسٹریشن سرٹیفکیٹ بعد وچ وی جوڑ سکدے او۔', upload: 'رجسٹریشن سرٹیفکیٹ اپ لوڈ کرو (اختیاری)', button: 'میریاں پراڈکٹاں فعال کرو', done: 'سب کجھ فعال اے', doneText: 'بلاکڈ اکاؤنٹ دیاں ادائیگیاں شروع، تہاڈی ہیلتھ انشورنس آن تے تہاڈا کارڈ ایپ وچ چالو۔ پہلی ادائیگی:', payout: '992 یورو', steps: ['آمد دی تاریخ تصدیق شدہ', 'پتہ رجسٹر شدہ', 'بلاکڈ اکاؤنٹ فعال', 'ہیلتھ انشورنس فعال', 'بینک اکاؤنٹ تے کارڈ فعال'] },
};
export const PORTAL: Record<Locale, PortalCopy> = { en, ur, pa };
