// Kundenweg (Jan 20.09.: "geh einmal alles durch, was ein kunde auch durchgehen wuerde"): Startseite, Menue, Sprache, Preise,
// Produktseite, Funnel bis zur Registrierung und ins Portal (Ueberweisung, Dokumente, Aktivierung, Chat), Hilfe, Botschafts-
// Checkliste, Kontakt, Kredit, Guides. Jeder Schritt meldet PASS oder FAIL; Konsolen- und Seitenfehler werden gesammelt.
// Aufruf: BASE=http://127.0.0.1:4322 bun run scripts/qa/journey.ts [--w=390] [--out=ORDNER]
import puppeteer from 'puppeteer-core';
const BASE = process.env.BASE ?? 'http://127.0.0.1:4321';
const args = process.argv.slice(2);
const W = Number((args.find((a) => a.startsWith('--w=')) ?? '--w=1440').split('=')[1]);
const OUT = (args.find((a) => a.startsWith('--out=')) ?? '').split('=')[1];
const mobile = W < 700;
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: W, height: mobile ? 844 : 900, deviceScaleFactor: mobile ? 2 : 1, isMobile: mobile, hasTouch: mobile });
const errors: string[] = [];
page.on('pageerror', (e) => errors.push(`pageerror ${page.url().replace(BASE, '')}: ${String(e).slice(0, 160)}`));
page.on('console', (m) => { if (m.type() === 'error') errors.push(`console ${page.url().replace(BASE, '')}: ${m.text().slice(0, 160)}`); });
page.on('response', (r) => { if (r.status() >= 400 && r.url().startsWith(BASE)) errors.push(`${r.status()} ${r.url().replace(BASE, '')}`); });
let pass = 0, fail = 0; const shots: string[] = [];
const go = async (path: string) => { await page.goto(BASE + path, { waitUntil: 'networkidle0' }); };
const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
const shot = async (name: string) => { if (!OUT) return; await wait(800); const f = `${OUT}/${W}-${name}.png`; await page.screenshot({ path: f, fullPage: false }); shots.push(f); };
const click = async (sel: string) => { await page.waitForSelector(sel, { visible: true, timeout: 6000 }); await page.click(sel); };
const visible = (sel: string) => page.$eval(sel, (el) => { const r = (el as HTMLElement).getBoundingClientRect(); return r.width > 0 && r.height > 0 && !(el as HTMLElement).hidden; }).catch(() => false);
const text = (sel: string) => page.$eval(sel, (el) => (el as HTMLElement).innerText.trim()).catch(() => '');
const untilPath = (frag: string) => page.waitForFunction((f: string) => location.pathname.includes(f), { timeout: 8000 }, frag);
const step = async (name: string, fn: () => Promise<string | void>) => { try { const r = await fn(); pass++; console.log(`PASS ${name}${r ? ' · ' + r : ''}`); } catch (e) { fail++; console.log(`FAIL ${name} · ${String(e).slice(0, 200)}`); } };

await step('Startseite laedt, Menue mit fuenf Punkten', async () => { await go('/'); const n = await page.$$eval('.nav-link', (els) => els.length); if (n !== 5) throw new Error(`nav-links ${n}`); });
if (mobile) await step('Mobil-Menue oeffnet und schliesst', async () => { await click('[data-toggle-nav]'); await wait(350); const open = await page.$eval('[data-nav]', (el) => el.classList.contains('open')); if (!open) throw new Error('nicht offen'); await shot('menu'); await page.keyboard.press('Escape'); await wait(300); const still = await page.$eval('[data-nav]', (el) => el.classList.contains('open')); if (still) throw new Error('nicht geschlossen'); });
await step('Sprache Urdu: RTL', async () => { await go('/'); const href = await page.$eval('.lang a[hreflang="ur"]', (a) => (a as HTMLAnchorElement).getAttribute('href')); await go(href!); const dir = await page.$eval('html', (h) => h.getAttribute('dir')); if (dir !== 'rtl') throw new Error('dir=' + dir); return href!; });
await step('Preise: PKR-Umschalter, Rechner, FAQ', async () => { await go('/pricing'); await click('[data-cur-btn="pkr"]'); await wait(700); /* die Betraege laufen 550 ms weich um (tween.ts, 27) */ const v = await text('[data-money]'); if (!v.startsWith('PKR')) throw new Error('kein PKR: ' + v); const t0 = await text('[data-eur=total]'); await page.$eval('[data-age]', (el) => { (el as HTMLInputElement).value = '35'; el.dispatchEvent(new Event('input', { bubbles: true })); }); const t1 = await text('[data-eur=total]'); if (t0 === t1) throw new Error('Rechner reagiert nicht'); await click('#faq details summary'); const open = await page.$$eval('#faq details[open]', (els) => els.length); if (!open) throw new Error('FAQ oeffnet nicht'); await shot('pricing'); return `${t0} -> ${t1}`; });
await step('Complete Setup: Hero-CTA fuehrt in den Funnel', async () => { await go('/complete-setup'); const href = await page.$eval('main a.btn', (a) => (a as HTMLAnchorElement).getAttribute('href')); if (!href?.endsWith('/app/start')) throw new Error('href ' + href); if (mobile) { await page.evaluate(() => window.scrollTo(0, 1400)); await wait(600); const cta = await page.$eval('[data-mobile-cta]', (el) => el.classList.contains('is-visible')); if (!cta) throw new Error('Mobil-CTA nicht sichtbar'); } return href; });
await step('Funnel: Fragen bis zum Ergebnis', async () => { await go('/app/start'); await click('[data-step="start"] [data-next]'); await shot('funnel-purpose'); await click('[data-answer="purpose"][data-value="0"]'); await click('[data-answer="from"][data-value="karachi"]'); await page.type('[data-answer="age"]', '23'); await click('[data-step="age"] [data-next]'); await page.$eval('[data-answer="arrival"]', (el) => { (el as HTMLInputElement).value = '2027-03'; el.dispatchEvent(new Event('change', { bubbles: true })); }); await click('[data-step="arrival"] [data-goto]'); await click('[data-answer="funding"][data-value="have"]'); await page.type('[data-answer="email"]', 'areeba@example.com'); await click('[data-step="email"] .btn-primary'); if (!(await visible('[data-step="result"]'))) throw new Error('kein Ergebnis'); await shot('funnel-result'); return await text('[data-out="totalEur"]'); });
await step('Funnel: Registrierung prueft Eingaben', async () => { await click('[data-goto="account"]'); if (!(await visible('[data-step="account"]'))) throw new Error('kein Kontoschritt'); const mirrored = await page.$eval('[data-mirror="email"]', (el) => (el as HTMLInputElement).value); await page.$eval('[data-mirror="email"]', (el) => { (el as HTMLInputElement).value = ''; }); await click('[data-acct] button[type="submit"]'); await wait(150); const e1 = await visible('[data-err="email"]'); if (!e1) throw new Error('kein E-Mail-Fehler'); await page.type('[data-mirror="email"]', 'areeba@example.com'); await page.type('[data-pw]', 'Kar'); await click('[data-acct] button[type="submit"]'); await wait(150); const e2 = await visible('[data-err="pw"]'); if (!e2) throw new Error('kein Passwort-Fehler'); await page.type('[data-pw]', 'achi2026!'); const meter = await page.$eval('[data-meter]', (el) => el.className); await click('[data-pw-toggle]'); const typ = await page.$eval('[data-pw]', (el) => (el as HTMLInputElement).type); if (typ !== 'text') throw new Error('Anzeige klappt nicht'); await shot('funnel-account'); return `mirror=${mirrored} meter=${meter}`; });
await step('Funnel: Konto angelegt, Erfolgsschritt, Portal', async () => { await click('[data-acct] button[type="submit"]'); await wait(400); if (!(await visible('[data-step="done"]'))) throw new Error('kein Erfolgsschritt'); const back = await page.$eval('[data-back]', (el) => (el as HTMLElement).hidden); await wait(900); await shot('funnel-done'); await click('[data-step="done"] a.btn-primary'); await untilPath('/app/dashboard'); await wait(700); /* Seitenwechsel per Router (M13): der Morph laeuft 400 ms, solange nimmt der Browser keine Klicks an */ return `back hidden=${back}`; });
await step('Dashboard laedt, Chat antwortet', async () => { await page.waitForSelector('.grid-a .next', { visible: true, timeout: 6000 }); await shot('dashboard'); await click(mobile ? '.ama-top' : '.ama'); await wait(200); if (!(await visible('[data-ama-panel]'))) throw new Error('Chat oeffnet nicht'); await click('[data-ama-q="1"]'); await wait(800); const n = await page.$$eval('[data-ama-log] .msg.them', (els) => els.length); if (n < 2) throw new Error('keine Antwort'); await page.keyboard.press('Escape'); return `${n} Antworten`; });
await step('Ueberweisung: kopieren, "gesendet" markieren', async () => { await go('/app/transfer'); const before = await text('[data-copy]'); await click('[data-copy]'); await wait(120); const after = await text('[data-copy]'); if (before === after) throw new Error('kein Kopiert-Hinweis'); await click('[data-sent]'); await wait(200); if (!(await visible('[data-sent-done]'))) throw new Error('keine Bestaetigung'); const done = await page.$$eval('[data-track] li.done', (els) => els.length); await shot('transfer'); return `${before} -> ${after}, ${done} Schritte erledigt`; });
await step('Dokumente: Download vorhanden, Vorschau', async () => { await go('/app/documents'); const n = await page.$$eval('.docs a.btn', (els) => els.length); if (n < 1) throw new Error('kein Download'); const prev = await visible('.preview'); if (!prev) throw new Error('keine Vorschau'); return `${n} Download`; });
await step('Aktivierung: Formular, Erfolg', async () => { await go('/app/activate'); await page.$eval('[data-activate] input[type="date"]', (el) => { (el as HTMLInputElement).value = '2027-03-08'; }); await page.type('[data-activate] input[type="text"]', 'Musterstraße 1, 10178 Berlin'); await click('[data-activate] button[type="submit"]'); await wait(200); if (!(await visible('[data-done]'))) throw new Error('kein Erfolg'); await shot('activate-done'); });
await step('Login: Pruefung, Passwort anzeigen, weiter ins Portal', async () => { await go('/app/login'); await click('[data-login] button[type="submit"]'); await wait(150); if (!(await visible('[data-err="email"]'))) throw new Error('kein E-Mail-Fehler'); await page.type('[data-login] input[type="email"]', 'areeba@example.com'); await page.type('[data-login] [data-pw]', 'Karachi2026!'); await click('[data-login] [data-pw-toggle]'); const typ = await page.$eval('[data-login] [data-pw]', (el) => (el as HTMLInputElement).type); if (typ !== 'text') throw new Error('Anzeige klappt nicht'); await shot('login'); await click('[data-login] button[type="submit"]'); await untilPath('/app/dashboard'); await wait(600); });
await step('Hilfe: Suche, kein Treffer, Themen', async () => { await go('/help'); await wait(1300); const c0 = await text('[data-results]'); const total = await page.$$eval('details.q', (els) => els.length); if (!c0.startsWith(String(total))) throw new Error(`Zaehler ${c0} bei ${total} Fragen`); await page.type('input[type="search"]', 'deposit'); await wait(200); const c1 = await text('[data-results]'); const vis1 = await page.$$eval('details.q', (els) => els.filter((d) => !(d as HTMLElement).hidden).length); if (!c1.startsWith(String(vis1))) throw new Error(`Zaehler ${c1} bei ${vis1} sichtbar`); await page.$eval('input[type="search"]', (el) => { (el as HTMLInputElement).value = 'zzzz'; el.dispatchEvent(new Event('input', { bubbles: true })); }); await wait(150); if (!(await visible('[data-none]'))) throw new Error('kein Hinweis bei 0 Treffern'); await page.$eval('input[type="search"]', (el) => { (el as HTMLInputElement).value = ''; el.dispatchEvent(new Event('input', { bubbles: true })); }); await wait(100); await click('[data-cat]:nth-of-type(3)'); await wait(150); const c2 = await text('[data-results]'); if (c2 === c0) throw new Error('Thema filtert nicht'); await shot('help'); return `${c0} / ${c1} / ${c2}`; });
await step('Botschafts-Checkliste: Visumtyp, Haken bleibt', async () => { await go('/embassy-checklist'); const n0 = await page.$$eval('[data-out=docs] li', (els) => els.length); await click('[data-group="work"]'); await wait(100); const n1 = await page.$$eval('[data-out=docs] li', (els) => els.length); if (n0 === n1) throw new Error('Liste wechselt nicht'); await click('[data-out=docs] input[type="checkbox"]'); await go('/embassy-checklist'); await click('[data-group="work"]'); await wait(100); const kept = await page.$eval('[data-out=docs] input[type="checkbox"]', (el) => (el as HTMLInputElement).checked); if (!kept) throw new Error('Haken nicht gespeichert'); await shot('embassy'); return `${n0} -> ${n1} Dokumente`; });
await step('Kontakt: Formular bestaetigt', async () => { await go('/help/contact'); await page.type('form[data-ack] input[type="email"]', 'areeba@example.com'); const subj = await page.$('form[data-ack] input[type="text"]'); if (subj) await subj.type('Question about the deposit'); await page.type('form[data-ack] textarea', 'When does the letter arrive?'); await click('form[data-ack] button[type="submit"]'); await wait(200); if (!(await visible('form[data-ack] .ack'))) throw new Error('keine Bestaetigung'); await shot('contact'); });
await step('Kredit: Anker und Bonus', async () => { await go('/study-loan'); await click('a[href="#how-it-works"]'); await wait(300); const h = await page.evaluate(() => location.hash); if (h !== '#how-it-works') throw new Error('hash ' + h); const bonus = await visible('.bonus-card'); if (!bonus) throw new Error('Bonuskarte fehlt'); });
await step('Guides: Thema, Artikel, Lesefortschritt', async () => { await go('/guides'); await click('.tags a'); await untilPath('/guides/tag/'); await wait(200); const cards = await page.$$eval('.card', (els) => els.length); if (cards < 1) throw new Error('keine Karten'); await go('/guides/german-student-visa'); await page.evaluate(() => window.scrollTo(0, 1200)); await wait(300); const w = await page.$eval('[data-readbar] i', (el) => getComputedStyle(el).transform); if (w === 'none' || w.includes('matrix(0,')) throw new Error('Lesefortschritt bleibt 0'); return `${cards} Karten im Thema`; });
await step('Header: Login-Link fuer Bestandskunden', async () => { await go('/'); if (mobile) { await click('[data-toggle-nav]'); await wait(350); } const href = await page.$eval('.header .login', (a) => (a as HTMLAnchorElement).getAttribute('href')); if (!href?.endsWith('/app/login')) throw new Error('href ' + href); if (mobile) { await page.keyboard.press('Escape'); } return href; });
await step('Demo-Konto "In Germany": Kontostand, IBAN, Karte einfrieren', async () => { await go('/app/login'); await click('[data-persona-go="active"]'); await untilPath('/app/dashboard'); await wait(400); const persona = await page.evaluate(() => document.documentElement.dataset.persona); if (persona !== 'active') throw new Error('persona ' + persona); if (!(await visible('.balance'))) throw new Error('keine Kontokarte'); if (await visible('.grid-a')) throw new Error('Zustand A sichtbar'); const bal = await text('.balance .amount'); await click('.balance [data-copy]'); await wait(150); const copied = await text('.balance [data-copy]'); await click('[data-freeze]'); await wait(200); const frozen = await page.$eval('.bal-card', (el) => el.classList.contains('frozen')); if (!frozen) throw new Error('Einfrieren klappt nicht'); await click('[data-freeze]'); await shot('dashboard-active'); const tx = await page.$$eval('.txlist li', (els) => els.length); return `${bal} · ${copied} · ${tx} Buchungen`; });
await step('Demo-Konto "In Germany": Ueberweisung, Dokumente, Aktivierung', async () => { await go('/app/transfer'); await wait(200); const done = await page.$$eval('[data-track] li.done', (els) => els.length); if (done !== 4) throw new Error(`track ${done}/4`); if (!(await visible('.received'))) throw new Error('kein Empfangshinweis'); if (await visible('[data-sent]')) throw new Error('Sendeknopf sichtbar'); await go('/app/documents'); await wait(200); const dl = await page.$$eval('.docs a.btn', (els) => els.filter((e) => (e as HTMLElement).offsetParent !== null).length); if (dl !== 4) throw new Error(`downloads ${dl}/4`); await go('/app/activate'); await wait(200); if (await visible('[data-activate]')) throw new Error('Formular sichtbar'); if (!(await visible('.done.only-active'))) throw new Error('kein Erledigt-Zustand'); await shot('activate-active'); return `${done} Schritte, ${dl} Downloads`; });
await step('Umschalter in der Seitenleiste zurueck auf "Before departure"', async () => { await go('/app/dashboard'); await click('[data-persona-set="applying"]'); await wait(400); const persona = await page.evaluate(() => document.documentElement.dataset.persona); if (persona !== 'applying') throw new Error('persona ' + persona); if (!(await visible('.grid-a .next'))) throw new Error('Zustand A fehlt'); if (await visible('.balance')) throw new Error('Kontokarte sichtbar'); const stored = await page.evaluate(() => localStorage.getItem('ec-persona')); await click('[data-bell]'); await wait(200); const notes = await page.$$eval('[data-bell-panel] ul.only-applying li', (els) => els.length); if (!(await visible('[data-bell-panel]'))) throw new Error('Glocke oeffnet nicht'); await shot('dashboard-applying'); return `gespeichert=${stored}, ${notes} Hinweise`; });
await step('Footer: Store-Badges und Social-Links', async () => { await go('/'); const b = await page.$$eval('footer .stores img', (els) => els.length); const s = await page.$$eval('footer .social a', (els) => els.length); if (b !== 2 || s < 4) throw new Error(`badges ${b} social ${s}`); });
// M02: eine Demo-Welt. Kein Objekt (Brief, Zertifikat, App-Screen, Portal, Behoerden-Verifikation) darf alte Literale zeigen; das Ausstellungsdatum des Briefs ist auf /authorities dasselbe.
await step('Demo-Welt ohne Widersprueche', async () => { const BAD = ['12 August 2026', '1,240.50', 'DE00 0000', '€138', '1 Oct', '3 Oct 2026']; const check = async (where: string) => { const body: string = await page.evaluate(() => document.body.innerText); const hit = BAD.filter((b) => body.includes(b)); if (hit.length) throw new Error(`${where}: ${hit.join(', ')}`); }; const dateOf = (s: string) => s.match(/\d{1,2} [A-Za-z]+ \d{4}/)?.[0] ?? ''; await go('/'); await check('/'); await go('/blocked-account'); await check('/blocked-account'); const ref = await text('.doc-stage .ref'); const docDate = dateOf(await text('.doc-stage .meta')); if (!docDate) throw new Error('kein Datum im Brief'); await go('/app/login'); await click('[data-persona-go="active"]'); await untilPath('/app/dashboard'); await wait(400); await check('/app/dashboard'); await go('/app/documents'); await wait(200); await check('/app/documents'); await go('/authorities'); await page.type('[data-verify] [name=ref]', ref); await click('[data-verify] button[type="submit"]'); await wait(150); if (!(await visible('[data-ok]'))) throw new Error('Verifikation kennt ' + ref + ' nicht'); await check('/authorities'); const authDate = dateOf(await text('[data-ok] [data-issued]')); if (authDate !== docDate) throw new Error(`Brief ${docDate} vs Behoerde ${authDate}`); return `${ref}, ausgestellt ${docDate} (Brief = Behoerde)`; });
// M11: Funnel-Zustand in URL und Session (Reload bleibt beim Ergebnis), Vorauswahl per ?group=, Browser-Zurueck geht im Funnel zurueck
await step('Funnel: Reload auf dem Ergebnis bleibt beim Ergebnis', async () => { await go('/app/start'); await click('[data-step="start"] [data-next]'); await click('[data-answer="purpose"][data-value="1"]'); await click('[data-answer="from"][data-value="islamabad"]'); await click('[data-step="age"] [data-next]'); await click('[data-step="arrival"] [data-goto]'); await click('[data-answer="funding"][data-value="have"]'); await click('[data-step="email"] .btn-link'); if (!(await visible('[data-step="result"]'))) throw new Error('kein Ergebnis'); const url0 = page.url().replace(BASE, ''); if (!url0.includes('step=result') || !url0.includes('plan=')) throw new Error('URL ohne step/plan: ' + url0); await page.reload({ waitUntil: 'networkidle0' }); await wait(300); if (!(await visible('[data-step="result"]'))) throw new Error('nach Reload kein Ergebnis'); const total = await text('[data-out="totalEur"]'); await shot('funnel-reload'); return `${url0.slice(0, 48)}… · ${total}`; });
await step('Funnel: ?group=work landet bei der Zweckfrage mit Vorauswahl', async () => { await go('/app/start?group=work'); await wait(200); if (!(await visible('[data-step="purpose"]'))) throw new Error('nicht bei der Zweckfrage'); const on = await page.$('[data-answer="purpose"][data-value="7"].is-on[aria-pressed="true"]'); if (!on) throw new Error('Arbeit nicht vorgewaehlt'); const dep = await page.$eval('[data-plan="deposit"]', (el) => (el as HTMLElement).textContent?.trim()); const q = await text('[data-count]'); return `${q} · deposit ${dep}`; });
await step('Funnel: Browser-Zurueck nach zwei Antworten zeigt den vorigen Schritt', async () => { await go('/app/start'); await click('[data-step="start"] [data-next]'); await click('[data-answer="purpose"][data-value="0"]'); await click('[data-answer="from"][data-value="karachi"]'); await page.waitForSelector('[data-step="age"]', { visible: true, timeout: 6000 }); await page.goBack({ waitUntil: 'load', timeout: 5000 }).catch(() => {}); await wait(500); if (!(await visible('[data-step="from"]'))) throw new Error('nicht beim vorigen Schritt'); if (await visible('[data-step="age"]')) throw new Error('Altersschritt noch sichtbar'); const on = await page.$('[data-answer="from"][data-value="karachi"].is-on'); return `${await text('[data-count]')} · Antwort markiert=${!!on} · ${page.url().replace(BASE, '')}`; });
await step('Seitenwechsel: Header-CTA fuehrt per Router in den Funnel, der Funnel bindet nach dem Tausch (M13)', async () => { await go('/'); if (mobile) { await click('[data-toggle-nav]'); await wait(350); } await click('.header .cta'); await untilPath('/app/start'); await wait(700); await click('[data-step="start"] [data-next]'); await wait(300); if (!(await visible('[data-step="purpose"]'))) throw new Error('Funnel reagiert nach dem Seitenwechsel nicht'); const vt = await page.evaluate(() => getComputedStyle(document.querySelector('.app-head')!).viewTransitionName); return `view-transition-name ${vt}`; });
console.log(`\n${pass} PASS, ${fail} FAIL, Fehler: ${errors.length ? '\n  ' + errors.join('\n  ') : 'keine'}`);
if (shots.length) console.log('Screenshots:', shots.length);
await browser.close();
